---
name: Build & Deploy
on:
    pull_request:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out the repository
              uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Lint with flake8
              run: |
                  # exit-zero treats all errors as warnings. The GitHub editor is 88 chars wide
                  flake8 . --count --statistics
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out the repository
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install Poetry
              uses: snok/install-poetry@v1
            - name: Install dependencies
              run: poetry install --no-dev
            - name: Test with pytest
              run: |
                  poetry run pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html --cov-fail-under=80 --suppress-no-test-exit-code
                  poetry run coverage xml -i
                  cp -f coverage.xml coverage/
            - uses: hipagesgroup/actions/coverage@master
              with:
                  coverage_dir: coverage/
    scan:
        name: Run Code Quality Scan 🔍
        runs-on: ubuntu-latest
        needs: [build, lint, test]
        timeout-minutes: 10
        steps:
            - name: Checkout
              uses: hipagesgroup/actions/checkout@master
              with:
                  fetch-depth: 0

            - name: Run code quality scanner
              uses: hipagesgroup/actions/code-quality@master
              with:
      # default = wait for quality gate on master only
                  wait: ${{ github.ref_name == 'master' && true || false }}
                  coverage_dir: coverage
                  sonar_token: ${{ secrets.SONAR_TOKEN }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}

    deploy:
        name: deploy
        runs-on: ubuntu-latest
        needs: [build]
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/regression-tests'
    #     environment:
    #       # @see https://github.community/t/do-expressions-support-ternary-operators-to-change-their-returned-value/18114/4
    #       name: ${{ fromJSON('["staging", "production"]')[github.ref == 'refs/heads/master'] }}
    #       url: ${{ steps.argocd.outputs.externalURL }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

      # - uses: hipagesgroup/actions/argocd@legacy
      #   id: argocd
      #   with:
      #     args: app-deploy
      #     server: ${{ secrets.ARGOCD_SERVER }}
      #     authToken: ${{ secrets.ARGOCD_AUTH_TOKEN }}
      #   env:
      #     IMAGE_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}
      #     IMAGE_TAG: ${{ github.sha }}
