---
name: Publish TechDocs Site

on:
    push:
        branches: [master]
        paths:
            - docs/**
            - mkdocs.yml

jobs:
    publish-techdocs-site:
        runs-on: ubuntu-latest

        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true

        env:
            TECHDOCS_S3_BUCKET_NAME: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
            AWS_ACCESS_KEY_ID: ${{ secrets.TECHDOCS_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.TECHDOCS_AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.TECHDOCS_AWS_REGION }}
            ENTITY_NAMESPACE: default
            ENTITY_KIND: Component
            ENTITY_NAME: ${{ github.event.repository.name }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2.4.0
            - uses: actions/setup-python@v2

            - name: Install techdocs-cli
              run: sudo npm install -g @techdocs/cli

            - name: Install mkdocs and mkdocs plugins
              run: python -m pip install mkdocs-techdocs-core==1.* mkdocs-minify-plugin mkdocs-markdownextradata-plugin mkdocs-macros-plugin

            - name: Generate docs site
              run: techdocs-cli generate --no-docker --verbose

            - name: Publish docs site
              run: techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
